channels:
- conda-forge
- defaults
dependencies:
- jupyterlab=4.4.2
- jupyterlab_vim=4.1.4
- lifelines=0.30.0
- matplotlib=3.10.3
- networkx=3.4.2
- pandas=2.2.3
- python=3.12.10
- scikit-learn=1.6.1
- scipy=1.15.2
- simpleitk=2.5.0
- tensorboard=2.19.0
- pip:
  - aiohappyeyeballs==2.6.1
  - aiohttp==3.11.18
  - aiosignal==1.3.2
  - click==8.2.0
  - dataclasses==0.6
  - filelock==3.18.0
  - frozenlist==1.6.0
  - fsspec==2025.3.2
  - huggingface-hub==0.31.2
  - imageio==2.37.0
  - ipywidgets==8.1.7
  - itk==5.4.3
  - itk-core==5.4.3
  - itk-filtering==5.4.3
  - itk-io==5.4.3
  - itk-numerics==5.4.3
  - itk-registration==5.4.3
  - itk-segmentation==5.4.3
  - jupyter==1.1.1
  - jupyter-console==6.6.3
  - jupyterlab-widgets==3.0.15
  - lazy-loader==0.4
  - lighter-zoo==0.1.3
  - lightning==2.5.1.post0
  - lightning-utilities==0.14.3
  - monai==1.4.0
  - mpmath==1.3.0
  - multidict==6.4.3
  - nibabel==5.3.2
  - notebook==7.4.2
  - numpy==1.26.4
  - nvidia-cublas-cu12==12.6.4.1
  - nvidia-cuda-cupti-cu12==12.6.80
  - nvidia-cuda-nvrtc-cu12==12.6.77
  - nvidia-cuda-runtime-cu12==12.6.77
  - nvidia-cudnn-cu12==9.5.1.17
  - nvidia-cufft-cu12==11.3.0.4
  - nvidia-cufile-cu12==1.11.1.6
  - nvidia-curand-cu12==10.3.7.77
  - nvidia-cusolver-cu12==11.7.1.2
  - nvidia-cusparse-cu12==12.5.4.2
  - nvidia-cusparselt-cu12==0.6.3
  - nvidia-nccl-cu12==2.26.2
  - nvidia-nvjitlink-cu12==12.6.85
  - nvidia-nvtx-cu12==12.6.77
  - opencv-python==4.11.0.86
  - packaging==24.2
  - pandocfilters==1.5.1
  - platipy==0.7.2
  - propcache==0.3.1
  - pydicom==2.4.4
  - pynetdicom==2.1.1
  - python-json-logger==3.3.0
  - pytorch-lightning==2.5.1.post0
  - rt-utils==1.2.7
  - safetensors==0.5.3
  - scikit-image==0.25.2
  - sympy==1.14.0
  - tifffile==2025.5.10
  - timm==1.0.15
  - torch==2.7.0
  - torch-geometric==2.6.1
  - torchaudio==2.7.0
  - torchmetrics==1.7.1
  - torchvision==0.22.0
  - tqdm==4.67.1
  - triton==3.3.0
  - types-python-dateutil==2.9.0.20250516
  - widgetsnbextension==4.0.14
  - yarl==1.20.0
name: pytorch_gpu_plus
